Add Component Description to Templating Engine
thomasa88/ParametricText pull request #63
Opened 2024-02-23 01:31 UTC by ProfDoof

Hi! I started using your add-in for a 3D model I needed but I wanted to be able to configure the text using the configurations feature. I didn't want to get to out into the weeds so I just leveraged the fact that configurations can change the description and used that. I would have used `_.component` however, the configurations table doesn't actually change the name of the root component, it simply uses that name for the configuration. (Or I'm doing something wrong) However, the description for the root component does get changed based on the configuration description.

2024-03-18 18:04 UTC, ProfDoof commented
@thomasa88, is there anything else I need to do for this PR? 

Side note: if there's anything you want tested, I have an education license and carte blanche for a lot of functionalities so I can test those.

2024-03-19 07:20 UTC, thomasa88 commented
Hi, I missed checking this PR in my last sweep. I'll see if I can get back to you in a few days. Skimming the change, I think I might want to rename the property to _.compdesc or similar, as I don't think the current name is specific enough.

2024-03-22 04:24 UTC, ProfDoof commented on ParametricText.py
> +{_.component}, {_.sketch}, {_.date}, {_.file}, {_.version}, {_.description}<br>
```suggestion
{_.component}, {_.sketch}, {_.date}, {_.file}, {_.version}, {_.compdesc}<br>
```

2024-03-22 04:24 UTC, ProfDoof commented on ParametricText.py
> +            elif member == 'description':
```suggestion
            elif member == 'compdesc':
```

2024-03-22 04:24 UTC, ProfDoof commented on docs/parameters.rst
> +| _.description | string   |Description  | Complex    |
```suggestion
| _.compdesc    | string   |Description  | Complex    |
```

2024-03-22 17:27 UTC, ProfDoof commented
Ok, @thomasa88, thanks! I went ahead and changed it to compdesc as my normal naming convention would probably have been `_.component.description` and that just felt like it would be too long. 

Quick question as I haven't had time to dig into this too much, but do these plugins support having outside dependencies? Because if so, you may consider just using a templating engine like jinja and ridding yourself of a bunch of the extra code maintenance cost.

2024-03-23 20:02 UTC, thomasa88 requested changes
Looks good overall! Thanks for submitting a nice patch.

I put a comment on handling the user changing the description.

Also, feel free to add your name and/or alias as a contributor:

```
diff --git a/docs/about.rst b/docs/about.rst
index ff0ae47..8ac6b4a 100644
--- a/docs/about.rst
+++ b/docs/about.rst
@@ -1,15 +1,20 @@
 Author & License
 ================
 
 Author
 ------
 
 This add-in is created by Thomas Axelsson.
 
+Contributors
+------------
+
+* Your Name and/or alias. Mix could be: "First Last (alias)"
+
 License
 -------
 
 This project is licensed under the terms of the MIT license.
```

2024-03-23 21:09 UTC, thomasa88 commented
> Quick question as I haven't had time to dig into this too much, but do these plugins support having outside dependencies? Because if so, you may consider just using a templating engine like jinja and ridding yourself of a bunch of the extra code maintenance cost.

It is possible to put python libs in the add-in directory. However, including time has to be done relative to the current directory, to avoid getting the wrong version of the libs, due to shared namespace for all python add-ins.

Can you explain your idea more? Where would jinja templates (?) be used? To replace the "variables" with expanded code?

2024-03-24 01:53 UTC, ProfDoof commented
So, the main benefit of using something like Jinja is currently you have a bunch of code for parsing the templates, and using something like Jinja would allow you to simplify your code to passing the correct context information to the template and then Jinja would handle actually rendering the string. It's not the most pressing enhancement but it would mean that in the future if you wanted to add support for something, you would just add to the context and then it would be available in the template instead of needing to handle parsing it.  

It also might come with performance benefits just by virtue of the library having worked with templating for.... a long time.

2024-03-24 14:47 UTC, merged

2024-03-24 14:53 UTC, thomasa88 commented
Thanks for the updates, now it's merged!

I replied to #58 about adding `_.configuration` and I'll wait some days to see if I get feedback on that, before I tag a new version and start the process of publishing an update to Autodesk.

Regarding Jinja, the add-in really needs some overhaul of the UX/UI as well. So if I get time to do that overhaul at some point, I'll take a look at Jinja too. Thanks for feedback.

2024-03-28 01:44 UTC, ProfDoof commented
No problem @thomasa88! There's a couple other templating engines as well, that's just the first one that came to mind. If you want any further input, feel free to @ me and I can share other things I've used or seen used.